package com.company.controller;

import com.company.entity.helpentity.InBuyerDistrictBuy;
import com.company.entity.tableentity.Buy;
import com.company.service.BuyService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.LinkedHashMap;
import java.util.List;

@RestController
@RequestMapping("/buy")
public class BuyController {
    @Autowired
    private BuyService buyService;

    @DeleteMapping("/delete/{id}")
    public void deleteBuy(@PathVariable int id){
        buyService.delete(id);
    }

    @PostMapping("/create")
    @ApiOperation("createBuy, id is generated by postgresql, leave the value at 0")
    public void createBuy(@RequestBody Buy buy){

        buyService.create(buy);
    }

    @GetMapping ("/find/all")
    public List<Buy> findAll () {
        List<Buy> list =  buyService.findAll();
        System.out.println(list);
        return list;
    }

    @GetMapping("/find/{id}")
    public Buy findById(@PathVariable int id){
        return buyService.findById(id);
    }

    @PutMapping("/updateFull")
    public void updateFull(@RequestBody Buy buy){
        buyService.updateFull(buy);
    }

    @PatchMapping("/update")
    public void update(@RequestParam int id,@RequestBody LinkedHashMap<String,String> data){
        buyService.update(id, data);
    }

    @GetMapping("/months")
    @ApiOperation("mamePrice, ex 2.c return set of months")
    public List<String> months(){
        return buyService.getMonth();
    }

    @GetMapping("/buyerNameStoreTitle")
    @ApiOperation("buyerNameStoreTitle, ex 4.a join buy with buyer and store")
    public List<String> buyerNameStoreTitle(){
        return buyService.getJoinTable();
    }

    @GetMapping("/buyerInfoBookInfo")
    @ApiOperation("buyerInfoBookInfo, ex 4.b join buy with buyer and book")
    public List<String> buyerInfoBookInfo(){
        return buyService.getBuyerBookInfo();
    }


    @GetMapping("/bigBuy/{sumMoreThan}")
    @ApiOperation("bigBuy, ex4.a return buy with sum > sumMoreThan")
    public List<String> bigBuy(@PathVariable int sumMoreThan){
        return buyService.getBigBuy(sumMoreThan);
    }

    @GetMapping("/bigBuy")
    @ApiOperation("bigBuy, ex4.a return buy with sum > 60000")
    public List<String> bigBuy(){
        return buyService.getBigBuy(60000);
    }

    @GetMapping("/buyInBuyerDistrict")
    @ApiOperation("bigBuy, ex4.b buy made by a buyer in his district no earlier than march")
    public List<InBuyerDistrictBuy> buyInBuyerDistrict(){
        return buyService.getBuyInBuyerDistrict();
    }
}
