package com.company.controller;

import com.company.controller.exception.NoContentException;
import com.company.entity.helpentity.NameDiscount;
import com.company.entity.tableentity.Buyer;
import com.company.service.BuyerService;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("buyer")
public class BuyerController {
    @Autowired
    private BuyerService buyerService;

    @DeleteMapping("/delete/{id}")
    public void deleteBuyer(@PathVariable int id){
        buyerService.delete(id);
    }

    @PostMapping("/create")
    @ApiOperation("createBuyer, id is generated by postgresql, leave the value at 0")
    public void createBuyer(@RequestBody Buyer buyer){
        System.out.println(buyer);
        buyerService.save(buyer);
    }

    @GetMapping ("/find/all")
    public List<Buyer> findAll () {
        return buyerService.findAll();
    }

    @GetMapping ("/find/{id}")
    @ApiResponses(value = {
            @ApiResponse(code = 204, message = "object with given id not found")
    }
    )
    public Buyer findById(@PathVariable int id){
        Optional<Buyer> optional = buyerService.findById(id);

        Buyer buyer = optional.orElse(null);

        if(buyer == null){
            throw new NoContentException();
        }

        return buyer;
    }

    @PutMapping ("/updateFull")
    public void updateFull(@RequestBody Buyer buyer){
        buyerService.updateFull(buyer);
    }

    @PatchMapping ("/update")
    public void update(@RequestParam int id,@RequestBody LinkedHashMap<String,String> data){
        buyerService.update(id, data);
    }

    @GetMapping ("/district")
    @ApiOperation("district, ex 2.b return set of districts")
    public List<String> district(){
        return buyerService.getDistricts();
    }

    @GetMapping("/discount")
    @ApiOperation("discount, ex 3.a return lastname, discount of buyers living in nizegorodskiy district")
    public List<NameDiscount> discount(){
        return buyerService.getNameDiscount();
    }
}
