package com.company.controller;

import com.company.controller.exception.NoContentException;
import com.company.entity.tableentity.Store;
import com.company.service.StoreService;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("store")
public class StoreController {
    @Autowired
    private StoreService storeService;

    @DeleteMapping("/delete/{id}")
    public void deleteStore(@PathVariable int id){
        storeService.delete(id);
    }

    @PostMapping("/create")
    @ApiOperation("createStore, id is generated by postgresql, leave the value at 0")
    public void createStore(@RequestBody Store store){
        storeService.save(store);
    }

    @GetMapping ("/find/all")
    public List<Store> findAll () {
        return storeService.findAll();
    }

    @GetMapping("/find/{id}")
    @ApiResponses(value = {
            @ApiResponse(code = 204, message = "object with given id not found")
    }
    )
    public Store findById(@PathVariable int id){
        Optional<Store> optional = storeService.findById(id);
        Store store = optional.orElse(null);

        if(store == null){
            throw new NoContentException();
        }

        return store;
    }

    @PutMapping("/updateFull")
    public void updateFull(@RequestBody Store store){
        storeService.updateFull(store);
    }

    @PatchMapping("/update")
    public void update(@RequestParam int id,@RequestBody LinkedHashMap<String,String> data){
        storeService.update(id, data);
    }

    @GetMapping("/storeTitle")
    @ApiOperation("storeTitle, ex 3.b return title of stores in sormovskiy,sovetskiy districts")
    public List<String> getTitles(){
        return storeService.getTitle();
    }

    @GetMapping("/storeByBuyerDiscount")
    @ApiOperation("storeByBuyerDiscount, ex 4.c")
    public List<Store> storeByBuyerDiscount(){
        //or use BuyJoin repository
        return storeService.getStoreConditionDiscount();
    }
}
