package com.company.controller;

import com.company.entity.tableentity.Store;
import com.company.service.StoreService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.LinkedHashMap;
import java.util.List;

@RestController
@RequestMapping("/store")
public class StoreController {
    @Autowired
    private StoreService storeService;

    @DeleteMapping("/delete/{id}")
    public void deleteStore(@PathVariable int id){
        storeService.delete(id);
    }

    @PostMapping("/create")
    @ApiOperation("createStore, id is generated by postgresql, leave the value at 0")
    public void createStore(@RequestBody Store store){
        storeService.save(store);
    }

    @GetMapping ("/find/all")
    public List<Store> findAll () {
        return storeService.findAll();
    }

    @GetMapping("/find/{id}")

    public Store findById(@PathVariable int id){
        return storeService.findById(id);
    }

    @PutMapping("/updateFull")
    public void updateFull(@RequestBody Store store){
        storeService.updateFull(store);
    }

    @PatchMapping("/update")
    public void update(@RequestParam int id,@RequestBody LinkedHashMap<String,String> data){
        storeService.update(id, data);
    }

    @GetMapping("/storeTitle")
    @ApiOperation("storeTitle, ex 3.b return title of stores in sormovskiy,sovetskiy districts")
    public List<String> getTitles(){
        return storeService.getTitle();
    }

    @GetMapping("/storeByBuyerDiscount")
    @ApiOperation("storeByBuyerDiscount, ex 4.c")
    public List<Store> storeByBuyerDiscount(){
        //or use BuyJoin repository
        return storeService.getStoreConditionDiscount();
    }
}
